from django.contrib import admin
from django.urls import path,include
from application import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('application.urls')), 
    path('code/', include('application.urls')), 
    path('about/', include('application.urls')),
    path('event1/', include('application.urls')),
    path('comsignup/', include('application.urls')),
    path('signup/', include('application.urls')),
    path('login/', include('application.urls')),
    path('feedback/', include('application.urls')),
    path('regcode/', include('application.urls')),
    path('showuser/', include('application.urls')),
    path('alert/', include('application.urls')),
    path('feedbackcode/', include('application.urls')),
    path('comsign/', include('application.urls')),
    path('welcome/', include('application.urls')),
    path('logout/', include('application.urls')),
    path('showcompany/', include('application.urls')),
    path('welcome1/', include('application.urls')),
    path('logout1/', include('application.urls')),
    path('admin1/', include('application.urls')),
    path('com/', include('application.urls')),
    path('login2/', include('application.urls')),
    path('add/', include('application.urls')),
    path('profile/', include('application.urls')),
    path('editprofile/', include('application.urls')),
    path('editsignup/', include('application.urls')),
    path('image/', include('application.urls')),
    path('addcode/', include('application.urls')),
    path('userpage/', include('application.urls')),
    path('event/', include('application.urls')),
    path('showuser2/', include('application.urls')),
    path('addimage/', include('application.urls')),
    path('account/', include('application.urls')),
    path('final/', include('application.urls')),
    path('signup/', include('application.urls')),
    path('final2/', include('application.urls')),
    path('final3/', include('application.urls')),
    path('companies/', include('application.urls')),
    path('showevents/', include('application.urls')),
    path('showeventscom/', include('application.urls')),
    path('showjobs/', include('application.urls')),
    path('showjobs2/', include('application.urls')),
    path('apply/', include('application.urls')),
    path('apply2/', include('application.urls')),
    path('apply3/', include('application.urls')),
    path('showresume/', include('application.urls')),
    path('showresume2/', include('application.urls')),
    path('applyevent/', include('application.urls')),
    path('eventapply/', include('application.urls')),
    path('myevent/', include('application.urls')),
    path('deleteevent/', include('application.urls')),
    path('feed/', include('application.urls')),
    path('deletefeed/', include('application.urls')),
    path('deletejob/', include('application.urls')),
    path('delevent/', include('application.urls')),
    path('may/', include('application.urls')),
    path('editjob/', include('application.urls')),
    path('editjobs/', include('application.urls')),
    path('editevent/', include('application.urls')),
    path('editevents/', include('application.urls')),
    path('final4/', include('application.urls')),
    path('resluts/', include('application.urls')),
    path('reslutcode/', include('application.urls')),
    path('showresults/', include('application.urls')),
    
    
]
